import { genesis3to10Studies } from "./genesis-3-10";

export interface VerseStudy {
  number: number;
  title: string;
  summary: string;
  hebrew: string;
  transliteration: string;
  rvr: string;
  ntv: string;
  lbla: string;
  exact: boolean;
  exegesis: string;
  language: string;
}

export type StudyConnection = readonly [reference: string, explanation: string];

export interface TheologyPoint {
  title: string;
  text: string;
}

export interface ChapterStudy {
  key: string;
  bookId: string;
  bookSlug: string;
  bookName: string;
  testament: string;
  section: string;
  chapter: number;
  chapterCount: number;
  lessonLabel: string;
  title: string;
  introduction: string;
  verses: VerseStudy[];
  theology: TheologyPoint[];
  doctrinalNote: string;
  connections: StudyConnection[];
}

const genesis1Verses: VerseStudy[] = [
  {
    number: 1,
    title: "El Creador y el comienzo",
    summary: "Dios inaugura la historia bíblica como sujeto soberano de toda la creación.",
    hebrew: "בְּרֵאשִׁית בָּרָא אֱלֹהִים",
    transliteration: "Bereshit bara Elohim",
    rvr: "“En el principio creó Dios los cielos y la tierra.”",
    ntv: "“En el principio, Dios creó los cielos y la tierra.”",
    lbla: "“En el principio creó Dios los cielos y la tierra.”",
    exact: true,
    exegesis: "La Biblia comienza con Dios, no intentando demostrar su existencia, sino presentándolo como el agente que inicia todo cuanto existe. «Los cielos y la tierra» funciona como una expresión totalizadora: comprende la realidad creada en su conjunto.",
    language: "Bereshit significa «en el principio». Bara describe aquí la acción creadora de Dios. Elohim tiene forma plural, pero el verbo está en singular; esta concordancia afirma un solo agente divino y, por sí sola, no constituye una demostración completa de la Trinidad.",
  },
  {
    number: 2,
    title: "La tierra sin ordenar",
    summary: "La escena inicial aparece deshabitada y sin ordenar, mientras el Espíritu de Dios se mueve sobre las aguas.",
    hebrew: "תֹהוּ וָבֹהוּ",
    transliteration: "Tohu va-vohu",
    rvr: "La tierra aparece desordenada y vacía; el Espíritu de Dios se mueve sobre las aguas.",
    ntv: "La creación todavía no tiene su forma habitable; el Espíritu de Dios está presente y activo.",
    lbla: "El relato presenta oscuridad, profundidad y una tierra aún sin forma ni población.",
    exact: false,
    exegesis: "El versículo no describe necesariamente una creación malvada ni una catástrofe previa. Presenta un mundo todavía no organizado para la vida. Los días siguientes mostrarán a Dios formando y llenando aquello que aquí aparece sin forma y vacío.",
    language: "Tohu va-vohu comunica desolación, falta de orden y ausencia de habitantes. Ruaj Elohim puede relacionarse con «Espíritu de Dios» y, según el contexto léxico, con «viento de Dios»; la imagen subraya la presencia divina sobre las aguas.",
  },
  {
    number: 3,
    title: "La palabra que crea",
    summary: "Dios ordena que exista la luz, y la realidad responde eficazmente a su palabra.",
    hebrew: "יְהִי אוֹר",
    transliteration: "Yehi or",
    rvr: "Dios pronuncia su mandato creador y aparece la luz.",
    ntv: "La palabra divina produce inmediatamente aquello que Dios dispone.",
    lbla: "La luz comienza a existir por la orden eficaz del Creador.",
    exact: false,
    exegesis: "El repetido «dijo Dios» establece uno de los ritmos fundamentales del capítulo. La creación no nace de una lucha entre divinidades: responde a la autoridad de la palabra del único Dios.",
    language: "La fórmula yehi or es breve y enfática: «sea luz». La correspondencia entre la orden y su cumplimiento comunica eficacia absoluta, no un deseo incierto.",
  },
  {
    number: 4,
    title: "Bondad y distinción",
    summary: "Dios reconoce la bondad de la luz y establece una distinción entre luz y oscuridad.",
    hebrew: "כִּי־טוֹב",
    transliteration: "Ki tov",
    rvr: "Dios declara buena la luz y la distingue de la oscuridad.",
    ntv: "El Creador evalúa su obra como buena y establece orden mediante separación.",
    lbla: "La valoración divina y la separación muestran propósito dentro de la creación.",
    exact: false,
    exegesis: "La bondad no es definida por una fuerza externa a Dios: el Creador evalúa su obra conforme a su propósito. Separar no implica que la oscuridad sea una divinidad rival, sino que Dios establece límites y funciones.",
    language: "Tov puede expresar bondad, adecuación o aquello que cumple correctamente su finalidad. La frase ki tov actúa como evaluación divina de la obra realizada.",
  },
  {
    number: 5,
    title: "El primer día",
    summary: "Dios nombra el día y la noche; tarde y mañana delimitan el primer ciclo del relato.",
    hebrew: "יוֹם אֶחָד",
    transliteration: "Yom ejad",
    rvr: "Dios nombra Día y Noche; la fórmula de tarde y mañana cierra el primer día.",
    ntv: "El primer ciclo queda definido por la alternancia de tarde y mañana.",
    lbla: "Nombrar manifiesta autoridad, y la fórmula temporal concluye la primera jornada.",
    exact: false,
    exegesis: "En el mundo antiguo, nombrar expresa autoridad. El cierre «tarde y mañana» organiza el relato en jornadas. La naturaleza precisa de estos días ha generado varias interpretaciones cristianas, pero todas deben comenzar por la función literaria de la secuencia en el texto.",
    language: "Yom puede referirse a un día ordinario o, en otros contextos, a un período. Aquí aparece acompañado por una fórmula numérica y temporal; su interpretación debe considerar tanto la gramática como la estructura completa de Génesis 1.",
  },
  {
    number: 6,
    title: "La expansión entre las aguas",
    summary: "Dios establece un espacio ordenado que distingue las aguas superiores de las inferiores.",
    hebrew: "יְהִי רָקִיעַ",
    transliteration: "Yehi raqia",
    rvr: "Dios ordena que exista una expansión en medio de las aguas.",
    ntv: "Dios dispone un espacio que separe unas aguas de otras.",
    lbla: "El Creador establece una bóveda para organizar las aguas.",
    exact: false,
    exegesis: "El segundo día continúa el movimiento desde lo no ordenado hacia un mundo habitable. La expansión no aparece como una divinidad celeste, sino como una parte de la creación que obedece al mandato de Dios.",
    language: "Raqia procede de una raíz asociada con extender o desplegar. Describe el espacio visible del cielo según la perspectiva del observador antiguo, sin convertir el pasaje en un tratado científico moderno.",
  },
  {
    number: 7,
    title: "Dios ejecuta su mandato",
    summary: "El mandato se convierte en obra: Dios hace la expansión y separa las aguas.",
    hebrew: "וַיַּבְדֵּל בֵּין הַמַּיִם",
    transliteration: "Vayavdel bein hamayim",
    rvr: "Dios realiza la separación entre las aguas de abajo y las de arriba.",
    ntv: "El Creador organiza las aguas conforme a la distinción ordenada.",
    lbla: "La obra divina cumple exactamente la palabra pronunciada.",
    exact: false,
    exegesis: "La repetición entre mandato y cumplimiento subraya que la voluntad divina no queda en intención. El relato atribuye directamente a Dios la formación del ámbito donde después aparecerán las criaturas voladoras.",
    language: "Badal significa separar o distinguir. En Génesis 1 la separación no destruye: establece límites que permiten identidad, función y vida.",
  },
  {
    number: 8,
    title: "El cielo recibe nombre",
    summary: "Dios llama cielos a la expansión y concluye el segundo día.",
    hebrew: "וַיִּקְרָא אֱלֹהִים לָרָקִיעַ שָׁמָיִם",
    transliteration: "Vayiqra Elohim laraqia shamayim",
    rvr: "Dios da a la expansión el nombre de cielos.",
    ntv: "El espacio creado recibe su identidad y función bajo la autoridad divina.",
    lbla: "La denominación del cielo confirma el señorío del Creador.",
    exact: false,
    exegesis: "Nombrar expresa autoridad soberana. El cielo que otras culturas podían divinizar queda aquí desmitificado: tiene nombre porque Dios se lo concede y ocupa el lugar que Dios determina.",
    language: "Shamayim es la palabra hebrea habitual para cielos o cielo. Su forma no exige por sí misma múltiples universos; el contexto determina si alude al firmamento visible o a los cielos en sentido amplio.",
  },
  {
    number: 9,
    title: "Aparece la tierra seca",
    summary: "Las aguas se reúnen en un lugar y queda visible el suelo habitable.",
    hebrew: "יִקָּווּ הַמַּיִם",
    transliteration: "Yiqqawu hamayim",
    rvr: "Dios reúne las aguas para que aparezca lo seco.",
    ntv: "El mar recibe límites y emerge la tierra donde habrá vida.",
    lbla: "La palabra divina delimita las aguas y descubre la tierra firme.",
    exact: false,
    exegesis: "El tercer día completa el ámbito terrestre. En vez de combatir un océano divino, Dios simplemente ordena las aguas. La aparición de lo seco prepara el escenario para la vegetación y, más adelante, para animales y seres humanos.",
    language: "El verbo qavah, aquí en forma pasiva-reflexiva, comunica reunión o concentración. La escena enfatiza delimitación, no aniquilación del mar.",
  },
  {
    number: 10,
    title: "Tierra y mares",
    summary: "Dios nombra los nuevos ámbitos y evalúa como buena su organización.",
    hebrew: "אֶרֶץ וּלְמִקְוֵה הַמַּיִם יַמִּים",
    transliteration: "Eretz ulemiqveh hamayim yamim",
    rvr: "Lo seco es llamado tierra y las aguas reunidas, mares.",
    ntv: "Dios asigna identidad a la tierra y al mar y declara buena su obra.",
    lbla: "La creación ordenada recibe nombre y aprobación divina.",
    exact: false,
    exegesis: "La valoración «bueno» indica que estos ámbitos cumplen el propósito asignado. El mar conserva fuerza y misterio en la Biblia, pero nunca aparece fuera del gobierno de Dios.",
    language: "Eretz puede significar tierra, territorio o suelo según el contexto. Yamim es el plural de yam, mar; ambos términos describen realidades creadas y subordinadas.",
  },
  {
    number: 11,
    title: "La tierra produce vegetación",
    summary: "Dios ordena que la tierra haga brotar plantas con semilla y árboles con fruto.",
    hebrew: "תַּדְשֵׁא הָאָרֶץ דֶּשֶׁא",
    transliteration: "Tadshe haaretz deshe",
    rvr: "La tierra recibe el mandato de producir hierba, semilla y fruto.",
    ntv: "Dios dota a la vegetación de continuidad y capacidad reproductiva.",
    lbla: "La fertilidad de la tierra responde a la palabra creadora.",
    exact: false,
    exegesis: "Dios concede a la creación una fecundidad real. La tierra participa como causa secundaria, pero la iniciativa y el diseño pertenecen al Creador. La semilla anticipa continuidad de generación en generación.",
    language: "Deshe designa vegetación tierna o verdor. La repetición sonora con el verbo producir refuerza literariamente la abundancia que comienza a cubrir la tierra.",
  },
  {
    number: 12,
    title: "Cada planta según su género",
    summary: "La tierra produce vegetación ordenada y Dios vuelve a declarar buena su obra.",
    hebrew: "לְמִינֵהוּ",
    transliteration: "Leminehu",
    rvr: "Las plantas y árboles producen conforme a sus géneros.",
    ntv: "La fecundidad creada conserva patrones reconocibles y continuidad.",
    lbla: "El orden vegetal manifiesta estabilidad dentro de la diversidad.",
    exact: false,
    exegesis: "«Según su género» describe orden reproductivo observable; no corresponde directamente a la taxonomía biológica moderna. El énfasis teológico está en una creación fecunda, diversa y no caótica.",
    language: "Min significa clase o género en sentido cotidiano antiguo. No debe equipararse sin más con especie en el sentido técnico contemporáneo.",
  },
  {
    number: 13,
    title: "El tercer día",
    summary: "Tarde y mañana cierran el día en que tierra, mares y vegetación quedan establecidos.",
    hebrew: "יוֹם שְׁלִישִׁי",
    transliteration: "Yom shelishi",
    rvr: "La fórmula temporal concluye el tercer día.",
    ntv: "El tercer ciclo creador termina con una tierra preparada para alimentar vida.",
    lbla: "El relato marca la conclusión ordenada de la tercera jornada.",
    exact: false,
    exegesis: "El tercer día contiene dos actos y dos evaluaciones de bondad: se forman los ámbitos terrestres y se inicia su llenado. Esta correspondencia contribuye a la arquitectura literaria del capítulo.",
    language: "Shelishi es el ordinal «tercero». La numeración funciona como marcador estructural y guía al lector a través de la secuencia creadora.",
  },
  {
    number: 14,
    title: "Luces para tiempos y estaciones",
    summary: "Dios coloca luminarias para distinguir día y noche y ordenar el calendario humano.",
    hebrew: "יְהִי מְאֹרֹת",
    transliteration: "Yehi meorot",
    rvr: "Dios ordena luminarias que sirvan como señales de tiempos, días y años.",
    ntv: "Los astros regulan ritmos de luz y calendario por designio del Creador.",
    lbla: "Las luces celestes reciben funciones temporales concretas.",
    exact: false,
    exegesis: "El texto evita los nombres habituales de sol y luna, posiblemente para negarles estatus divino. Son lámparas funcionales creadas por Dios, no poderes que gobiernan el destino humano.",
    language: "Meorot significa luminarias o portadores de luz. Moedim puede referirse a estaciones y también a tiempos señalados para reuniones o festividades.",
  },
  {
    number: 15,
    title: "Luz sobre la tierra",
    summary: "Las luminarias reciben la tarea práctica de alumbrar el mundo habitado.",
    hebrew: "לְהָאִיר עַל־הָאָרֶץ",
    transliteration: "Lehair al-haaretz",
    rvr: "Las luces del cielo alumbran sobre la tierra.",
    ntv: "Su función beneficia directamente al ámbito donde vivirán las criaturas.",
    lbla: "La iluminación terrestre cumple el mandato de Dios.",
    exact: false,
    exegesis: "La frase recalca finalidad y servicio. Los cuerpos celestes no son objetos de culto; existen para sostener los ritmos de la creación y servir al escenario de la vida.",
    language: "Hair es la forma causativa del verbo or, «dar luz». La construcción expresa propósito: fueron colocadas para iluminar.",
  },
  {
    number: 16,
    title: "Las dos grandes luminarias",
    summary: "Dios hace las luminarias mayor y menor, y también las estrellas.",
    hebrew: "שְׁנֵי הַמְּאֹרֹת הַגְּדֹלִים",
    transliteration: "Shenei hameorot hagedolim",
    rvr: "La luminaria mayor preside el día y la menor, la noche.",
    ntv: "Sol, luna y estrellas son presentados como obras, no como dioses.",
    lbla: "Cada luminaria recibe un ámbito de servicio bajo el Creador.",
    exact: false,
    exegesis: "La mención casi incidental de las estrellas contrasta con su importancia religiosa en el mundo antiguo. Aquello que las naciones temían o adoraban es, en Génesis, producto de la palabra divina.",
    language: "Gadol significa grande. El lenguaje de gobierno de las luminarias describe función en los ciclos del día y la noche, no soberanía independiente.",
  },
  {
    number: 17,
    title: "Colocadas por Dios",
    summary: "Dios sitúa las luminarias en la expansión para cumplir su misión sobre la tierra.",
    hebrew: "וַיִּתֵּן אֹתָם אֱלֹהִים",
    transliteration: "Vayitten otam Elohim",
    rvr: "Dios coloca las luminarias en el cielo.",
    ntv: "El Creador asigna a los astros su lugar y servicio.",
    lbla: "La ubicación de las luces responde a la intención divina.",
    exact: false,
    exegesis: "La acción personal de Dios domina el versículo. El cosmos no encuentra su lugar por voluntad propia: su estabilidad y utilidad proceden del orden que el Creador establece.",
    language: "Natan significa dar, poner o colocar. Aquí comunica asignación: Dios entrega a las luminarias un lugar y una tarea.",
  },
  {
    number: 18,
    title: "Gobierno sin divinización",
    summary: "Las luminarias regulan día y noche y mantienen la distinción entre luz y oscuridad.",
    hebrew: "וְלִמְשֹׁל בַּיּוֹם וּבַלַּיְלָה",
    transliteration: "Velimshol bayom uvalaylah",
    rvr: "Las luces gobiernan los ciclos del día y de la noche.",
    ntv: "Sirven para regular la luz y la oscuridad conforme al diseño divino.",
    lbla: "Su dominio es funcional y subordinado al mandato del Creador.",
    exact: false,
    exegesis: "El verbo gobernar no concede personalidad divina a los astros. Su autoridad es derivada: cumplen una función regular dentro de límites establecidos por Dios.",
    language: "Mashal puede significar gobernar o ejercer dominio. El infinitivo expresa la función asignada a las luminarias, siempre bajo la soberanía mayor de Dios.",
  },
  {
    number: 19,
    title: "El cuarto día",
    summary: "La cuarta jornada concluye con los ritmos celestes establecidos.",
    hebrew: "יוֹם רְבִיעִי",
    transliteration: "Yom revii",
    rvr: "Tarde y mañana cierran el cuarto día.",
    ntv: "El ciclo termina con el cielo ordenado para marcar los tiempos.",
    lbla: "La cuarta jornada completa la función de las luminarias.",
    exact: false,
    exegesis: "El cuarto día corresponde al primero: la luz y la oscuridad reciben ahora portadores que regulan sus ciclos. La estructura muestra una creación cuidadosamente formada y luego poblada.",
    language: "Revii significa «cuarto». Como los demás ordinales, mantiene el ritmo litúrgico y narrativo del capítulo.",
  },
  {
    number: 20,
    title: "Vida en aguas y cielos",
    summary: "Dios ordena abundancia de criaturas acuáticas y aves sobre la tierra.",
    hebrew: "יִשְׁרְצוּ הַמַּיִם שֶׁרֶץ",
    transliteration: "Yishretzu hamayim sheretz",
    rvr: "Las aguas reciben el mandato de llenarse de seres vivientes.",
    ntv: "La vida irrumpe en abundancia en el mar y en el cielo.",
    lbla: "Criaturas acuáticas y voladoras comienzan a poblar sus ámbitos.",
    exact: false,
    exegesis: "El día quinto inicia el llenado de los espacios formados en el segundo día. La abundancia no es accidente: constituye una expresión deliberada de la generosidad creadora.",
    language: "Sharatz expresa pulular o multiplicarse abundantemente. Nefesh hayyah, «ser viviente», destaca vida animada y no equivale automáticamente a la noción filosófica posterior de alma separable.",
  },
  {
    number: 21,
    title: "Los grandes seres marinos",
    summary: "Incluso las criaturas imponentes del mar son creadas y declaradas buenas por Dios.",
    hebrew: "הַתַּנִּינִם הַגְּדֹלִים",
    transliteration: "Hatanninim hagedolim",
    rvr: "Dios crea los grandes monstruos marinos y toda criatura acuática.",
    ntv: "Las criaturas más temidas del océano pertenecen al orden creado.",
    lbla: "Todo ser marino y toda ave existen por la acción de Dios.",
    exact: false,
    exegesis: "En mitos vecinos, seres marinos podían representar poderes rivales. Génesis los incluye entre los animales creados: no amenazan la soberanía divina ni participan en una batalla cósmica contra Dios.",
    language: "Tanninim puede designar grandes criaturas marinas, serpientes o dragones según el contexto. Aquí son animales creados y buenos, no deidades enemigas.",
  },
  {
    number: 22,
    title: "La primera bendición",
    summary: "Dios bendice a los animales y les ordena fructificar y multiplicarse.",
    hebrew: "פְּרוּ וּרְבוּ",
    transliteration: "Peru urevu",
    rvr: "Dios bendice la vida marina y las aves con fecundidad.",
    ntv: "La multiplicación de la vida procede de la bendición divina.",
    lbla: "Criaturas del mar y del cielo reciben capacidad para llenar sus ámbitos.",
    exact: false,
    exegesis: "La bendición es palabra eficaz que concede capacidad para cumplir el mandato. La vida no solo comienza; recibe de Dios continuidad, expansión y futuro.",
    language: "Parah y rabah significan fructificar y multiplicarse. Los imperativos comunican misión acompañada por la provisión divina necesaria para realizarla.",
  },
  {
    number: 23,
    title: "El quinto día",
    summary: "La jornada concluye con mares y cielos llenándose de vida bendecida.",
    hebrew: "יוֹם חֲמִישִׁי",
    transliteration: "Yom jamishi",
    rvr: "Tarde y mañana cierran el quinto día.",
    ntv: "El quinto ciclo termina después de la bendición de los animales.",
    lbla: "La quinta jornada completa el poblamiento de aguas y cielo.",
    exact: false,
    exegesis: "El quinto día corresponde al segundo: los ámbitos separados de aguas y expansión reciben ahora sus habitantes. La simetría literaria sostiene el mensaje de orden intencional.",
    language: "Jamishi es el ordinal «quinto». La forma repetida de cierre mantiene unidad y expectativa hacia el clímax del sexto día.",
  },
  {
    number: 24,
    title: "Seres vivientes de la tierra",
    summary: "La tierra produce animales domésticos, criaturas pequeñas y fauna salvaje.",
    hebrew: "תּוֹצֵא הָאָרֶץ נֶפֶשׁ חַיָּה",
    transliteration: "Totze haaretz nefesh hayyah",
    rvr: "Dios ordena que la tierra produzca seres vivientes según sus géneros.",
    ntv: "El ámbito terrestre se llena con una diversidad organizada de animales.",
    lbla: "La tierra responde al mandato divino produciendo vida animal.",
    exact: false,
    exegesis: "Las categorías reflejan la experiencia cotidiana del antiguo Israel, no una clasificación zoológica exhaustiva. El punto central es que toda forma de vida terrestre depende de la palabra de Dios.",
    language: "Behemah suele referirse a animales domésticos; remes, a criaturas que se desplazan cerca del suelo; jayto-eretz, a fauna del campo. Son categorías observacionales.",
  },
  {
    number: 25,
    title: "Diversidad bajo un solo Creador",
    summary: "Dios hace los distintos animales de la tierra y contempla que su obra es buena.",
    hebrew: "וַיַּעַשׂ אֱלֹהִים",
    transliteration: "Vayaas Elohim",
    rvr: "Dios hace cada grupo de animales según su género.",
    ntv: "La diversidad animal recibe forma y orden del Creador.",
    lbla: "La obra terrestre queda completa y aprobada como buena.",
    exact: false,
    exegesis: "El versículo repite que Dios hace y evalúa. La bondad de los animales precede a su utilidad para los humanos; poseen valor dentro del propósito creador de Dios.",
    language: "Asah, «hacer», aparece junto a bara en el capítulo. Los términos se solapan en parte y no deben convertirse automáticamente en etapas técnicas diferentes de creación.",
  },
  {
    number: 26,
    title: "La humanidad a imagen de Dios",
    summary: "Dios anuncia la creación humana a su imagen y le confía representación responsable sobre la tierra.",
    hebrew: "נַעֲשֶׂה אָדָם בְּצַלְמֵנוּ כִּדְמוּתֵנוּ",
    transliteration: "Naaseh adam betzalmenu kidmutenu",
    rvr: "Dios decide hacer al ser humano a su imagen y semejanza.",
    ntv: "La humanidad es creada para reflejar a Dios y administrar su mundo.",
    lbla: "Imagen, semejanza y dominio aparecen unidos en la vocación humana.",
    exact: false,
    exegesis: "El plural «hagamos» ha recibido varias explicaciones: deliberación divina, consejo celestial y lectura cristiana trinitaria. El versículo por sí solo no define toda la doctrina de la Trinidad, pero dentro del canon es compatible con la revelación posterior. La imagen implica dignidad y una misión representativa.",
    language: "Tselem es imagen o representación; demut, semejanza. Adam puede designar a la humanidad colectivamente antes de funcionar como nombre propio. Radah describe ejercer dominio, que debe imitar el cuidado del Rey divino.",
  },
  {
    number: 27,
    title: "Varón y mujer, imagen divina",
    summary: "Dios crea a la humanidad, masculina y femenina, compartiendo plenamente su imagen.",
    hebrew: "זָכָר וּנְקֵבָה בָּרָא אֹתָם",
    transliteration: "Zakhar uneqevah bara otam",
    rvr: "La humanidad es creada a imagen de Dios: varón y mujer.",
    ntv: "Ambos sexos reciben igual dignidad y la misma vocación ante el Creador.",
    lbla: "La imagen divina pertenece conjuntamente al hombre y a la mujer.",
    exact: false,
    exegesis: "La forma poética repite tres veces el acto creador y coloca la imagen de Dios en el centro. Ningún sexo posee una imagen más plena. La unidad humana incluye diferencia sexual sin jerarquía de valor.",
    language: "Zakhar y neqevah son términos sexuales complementarios. El pronombre plural «los» confirma que la expresión colectiva «el ser humano» comprende a ambos.",
  },
  {
    number: 28,
    title: "Bendición y mandato cultural",
    summary: "Dios bendice a la humanidad para multiplicarse, llenar la tierra y administrarla responsablemente.",
    hebrew: "מִלְאוּ אֶת־הָאָרֶץ וְכִבְשֻׁהָ",
    transliteration: "Milu et-haaretz vekivshuha",
    rvr: "La humanidad recibe fecundidad, dominio y responsabilidad sobre los seres vivos.",
    ntv: "Dios encomienda desarrollar la vida humana y cuidar el mundo bajo su autoridad.",
    lbla: "El mandato une bendición, expansión humana y gobierno de la creación.",
    exact: false,
    exegesis: "Sojuzgar y dominar no autorizan explotación destructiva. Como portadores de la imagen, los humanos representan al Rey cuyo gobierno produce orden y vida. El poder delegado permanece sujeto al carácter y mandato de Dios.",
    language: "Kabash puede expresar someter; radah, gobernar. En este contexto anterior al pecado describen ordenar y administrar una tierra buena, no violencia contra ella.",
  },
  {
    number: 29,
    title: "La provisión de alimento",
    summary: "Dios entrega plantas con semilla y frutos como alimento para la humanidad.",
    hebrew: "נָתַתִּי לָכֶם",
    transliteration: "Natati lakhem",
    rvr: "Dios concede la vegetación y los frutos para alimento.",
    ntv: "La provisión material aparece como un don anterior al esfuerzo humano.",
    lbla: "El Creador sostiene a sus representantes con los recursos de la tierra.",
    exact: false,
    exegesis: "El mandato humano viene acompañado de provisión. El texto presenta originalmente una dieta vegetal; otros pasajes, especialmente Génesis 9, desarrollarán posteriormente la cuestión alimentaria. No debe aislarse este versículo del movimiento total del canon.",
    language: "Natati es perfecto de natan, «he dado». La forma destaca que el alimento se recibe como don divino y no como posesión autónoma.",
  },
  {
    number: 30,
    title: "Dios alimenta a sus criaturas",
    summary: "La vegetación también sostiene a los animales terrestres y a las aves.",
    hebrew: "לְכָל־חַיַּת הָאָרֶץ",
    transliteration: "Lekhol jayat haaretz",
    rvr: "Dios provee alimento para toda criatura con aliento de vida.",
    ntv: "El cuidado creador se extiende más allá de la humanidad.",
    lbla: "Animales y aves participan de la provisión abundante de Dios.",
    exact: false,
    exegesis: "La providencia divina alcanza a toda la comunidad de criaturas. La humanidad ocupa una función singular, pero no es la única destinataria de la bondad del Creador.",
    language: "Kol significa «todo» o «cada». La repetición amplía deliberadamente el alcance de la provisión a los distintos grupos de seres vivientes.",
  },
  {
    number: 31,
    title: "Todo era muy bueno",
    summary: "Dios contempla la totalidad integrada de su obra y declara que es muy buena.",
    hebrew: "טוֹב מְאֹד",
    transliteration: "Tov meod",
    rvr: "Dios evalúa el conjunto de lo creado como muy bueno.",
    ntv: "La creación completa cumple abundantemente el propósito divino.",
    lbla: "La aprobación final alcanza a la totalidad ordenada del mundo.",
    exact: false,
    exegesis: "La evaluación final es más intensa que las anteriores porque contempla el sistema completo: ámbitos, habitantes, relaciones y vocaciones. El mal de los capítulos siguientes no pertenece al diseño original de Dios; irrumpe en una creación inicialmente buena.",
    language: "Meod intensifica tov: no solo bueno, sino muy bueno. Hashishi, «el sexto», aparece con artículo y cierra el clímax antes del reposo del séptimo día.",
  },
];

const genesis1Connections: StudyConnection[] = [
  ["Salmo 33:6", "La creación mediante la palabra del Señor."],
  ["Juan 1:1–3", "El prólogo identifica al Verbo como agente de la creación."],
  ["Colosenses 1:16", "Todas las cosas fueron creadas por medio de Cristo y para él."],
  ["Hebreos 11:3", "La fe reconoce que el universo fue constituido por la palabra de Dios."],
];

const genesis2Verses: VerseStudy[] = [
  {
    number: 1,
    title: "La creación llega a su plenitud",
    summary: "Los cielos, la tierra y todo su conjunto quedan terminados conforme al propósito divino.",
    hebrew: "וַיְכֻלּוּ הַשָּׁמַיִם וְהָאָרֶץ",
    transliteration: "Vayekhullu hashamayim vehaaretz",
    rvr: "La obra creadora aparece completa con todos sus habitantes y funciones.",
    ntv: "Dios concluye el universo ordenado que había dispuesto.",
    lbla: "El relato declara acabada la totalidad de los cielos y la tierra.",
    exact: false,
    exegesis: "El versículo funciona como conclusión de Génesis 1 y entrada al séptimo día. La creación no queda abandonada ni incompleta: alcanza la forma y el orden que Dios quiso darle.",
    language: "Vayekhullu procede de kalah, «completar» o «llevar a término». Tsevaam, «su ejército» o «su conjunto», abarca los habitantes ordenados del cosmos.",
  },
  {
    number: 2,
    title: "Dios cesa en el séptimo día",
    summary: "Dios termina su obra y cesa de la actividad creadora que había realizado.",
    hebrew: "וַיִּשְׁבֹּת בַּיּוֹם הַשְּׁבִיעִי",
    transliteration: "Vayishbot bayom hashvii",
    rvr: "Dios reposa en el séptimo día después de completar su obra.",
    ntv: "El Creador deja de crear porque su trabajo ha llegado a término.",
    lbla: "La cesación divina señala la consumación de la obra.",
    exact: false,
    exegesis: "El reposo no implica cansancio físico en Dios. Expresa cesación, satisfacción y gobierno sobre una creación completa. El séptimo día corona la semana y orienta el tiempo humano hacia la comunión con el Creador.",
    language: "Shavat significa principalmente «cesar» o «dejar de trabajar» y está relacionado con shabbat. El verbo describe el fin de una tarea, no recuperación por agotamiento.",
  },
  {
    number: 3,
    title: "Tiempo bendecido y apartado",
    summary: "Dios bendice el séptimo día y lo distingue porque en él cesó de crear.",
    hebrew: "וַיְבָרֶךְ אֱלֹהִים אֶת־יוֹם הַשְּׁבִיעִי",
    transliteration: "Vayevarekh Elohim et-yom hashvii",
    rvr: "El séptimo día recibe bendición y santidad de parte de Dios.",
    ntv: "Dios aparta ese día como señal de su obra completa.",
    lbla: "La bendición divina convierte el séptimo día en tiempo consagrado.",
    exact: false,
    exegesis: "Es la primera realidad llamada santa en la Biblia: no un lugar ni un objeto, sino un tiempo. Más adelante Israel recibirá el sábado como señal del pacto, pero aquí el patrón se arraiga en la creación.",
    language: "Qiddesh significa «santificar» o «separar para Dios». Barakh, «bendecir», comunica la capacidad otorgada por Dios para cumplir un propósito beneficioso.",
  },
  {
    number: 4,
    title: "La historia de los cielos y la tierra",
    summary: "Una fórmula de generaciones introduce una mirada cercana a la humanidad dentro de la creación.",
    hebrew: "אֵלֶּה תוֹלְדוֹת הַשָּׁמַיִם וְהָאָרֶץ",
    transliteration: "Elleh toledot hashamayim vehaaretz",
    rvr: "Comienza el desarrollo de la historia de los cielos y la tierra.",
    ntv: "El relato enfoca ahora cómo Dios formó al ser humano y su hogar.",
    lbla: "La fórmula literaria conecta la creación cósmica con la historia humana.",
    exact: false,
    exegesis: "Toledot organiza grandes secciones de Génesis. Génesis 2 no necesita leerse como una creación rival, sino como una ampliación temática que concentra la atención en la tierra, el jardín, la vocación y las relaciones humanas.",
    language: "Toledot puede significar «generaciones», «descendencia» o «historia resultante». El nombre compuesto YHWH Elohim aparece aquí de manera característica.",
  },
  {
    number: 5,
    title: "Una tierra que espera cultivo",
    summary: "El campo aún no está cultivado porque faltan lluvia y un ser humano que trabaje la tierra.",
    hebrew: "וְאָדָם אַיִן לַעֲבֹד אֶת־הָאֲדָמָה",
    transliteration: "Veadam ayin laavod et-haadamah",
    rvr: "La vegetación del campo espera lluvia y trabajo humano.",
    ntv: "La tierra cultivable todavía no produce porque no hay agricultor.",
    lbla: "El pasaje prepara la misión humana de servir la tierra.",
    exact: false,
    exegesis: "El texto describe el ámbito cultivable antes de la instalación del ser humano, no necesariamente la ausencia absoluta de toda vegetación de Génesis 1. La escena anticipa la interdependencia entre provisión divina y vocación humana.",
    language: "Adam, «ser humano», se relaciona sonoramente con adamah, «suelo». Avad significa «trabajar» y también «servir», dando profundidad espiritual a la labor humana.",
  },
  {
    number: 6,
    title: "La tierra recibe humedad",
    summary: "Una corriente o vapor sube de la tierra y riega la superficie del suelo.",
    hebrew: "וְאֵד יַעֲלֶה מִן־הָאָרֶץ",
    transliteration: "Veed yaaleh min-haaretz",
    rvr: "La humedad asciende y riega toda la superficie.",
    ntv: "Dios provee agua para preparar el suelo.",
    lbla: "Una corriente terrestre humedece la tierra antes del cultivo.",
    exact: false,
    exegesis: "La provisión de agua prepara el escenario para la formación del ser humano. El mecanismo exacto es secundario frente a la afirmación de que el ambiente vital depende del cuidado providencial de Dios.",
    language: "Ed es un término raro; puede referirse a «vapor», «niebla» o «corriente subterránea». Su escasa frecuencia aconseja evitar conclusiones meteorológicas rígidas.",
  },
  {
    number: 7,
    title: "Polvo animado por el aliento de Dios",
    summary: "Dios forma al ser humano del suelo y comunica vida mediante su aliento.",
    hebrew: "וַיִּיצֶר יְהוָה אֱלֹהִים אֶת־הָאָדָם",
    transliteration: "Vayyitser Adonai Elohim et-haadam",
    rvr: "El hombre es formado del polvo y recibe aliento de vida.",
    ntv: "Dios modela al ser humano y le comunica vida personalmente.",
    lbla: "La criatura terrenal se convierte en ser viviente por el soplo divino.",
    exact: false,
    exegesis: "La humanidad posee simultáneamente humildad y dignidad: procede del polvo, pero vive por el don inmediato de Dios. El versículo describe al ser humano como una unidad viviente, no como una colección de partes independientes.",
    language: "Yatsar es «formar» como un alfarero; afar es «polvo»; nishmat jayyim, «aliento de vida». Nephesh jayyah designa un ser viviente y también se usa para animales.",
  },
  {
    number: 8,
    title: "Un jardín preparado como hogar",
    summary: "Dios planta un jardín en Edén y coloca allí al ser humano que había formado.",
    hebrew: "וַיִּטַּע יְהוָה אֱלֹהִים גַּן־בְּעֵדֶן",
    transliteration: "Vayyita Adonai Elohim gan-beEden",
    rvr: "Dios planta un huerto y sitúa allí al hombre.",
    ntv: "El Creador prepara un lugar abundante para la vida humana.",
    lbla: "El jardín es don y esfera de responsabilidad.",
    exact: false,
    exegesis: "El jardín no es conquista humana, sino regalo divino. Dios coloca allí al hombre con una vocación concreta. La gracia precede a la obediencia: primero hay vida y provisión, después mandato.",
    language: "Gan significa «jardín cercado»; Eden se relaciona con «deleite». Sam, «puso», enfatiza una ubicación intencional.",
  },
  {
    number: 9,
    title: "Árboles, vida y discernimiento",
    summary: "Dios hace crecer árboles hermosos y buenos para alimento, destacando dos árboles centrales.",
    hebrew: "וְעֵץ הַחַיִּים בְּתוֹךְ הַגָּן",
    transliteration: "Veets hajayyim betokh hagan",
    rvr: "El jardín contiene el árbol de la vida y el del conocimiento del bien y del mal.",
    ntv: "La abundancia del huerto incluye una decisión moral bajo la palabra de Dios.",
    lbla: "Belleza, alimento, vida y límite aparecen unidos en el centro del jardín.",
    exact: false,
    exegesis: "Los árboles muestran la generosidad de Dios antes de presentar la prohibición. El conocimiento del bien y del mal puede expresar discernimiento moral o pretensión de autonomía; en el contexto, el problema no es aprender, sino definir el bien al margen del Creador.",
    language: "Nehmad lemareh significa «deseable a la vista»; tov lemaakal, «bueno para comer». Daat une bien y mal dentro de una expresión totalizadora.",
  },
  {
    number: 10,
    title: "Un río que comunica vida",
    summary: "Un río sale de Edén, riega el jardín y después se divide en cuatro brazos.",
    hebrew: "וְנָהָר יֹצֵא מֵעֵדֶן",
    transliteration: "Venahar yotse meEden",
    rvr: "El río de Edén riega el huerto y se reparte.",
    ntv: "La vida fluye desde el lugar provisto por Dios hacia otras tierras.",
    lbla: "El agua del jardín se convierte en fuente de amplitud geográfica.",
    exact: false,
    exegesis: "El río retrata abundancia que se extiende más allá del centro del jardín. Profetas y Apocalipsis retomarán el símbolo del agua que fluye desde la presencia divina para sanar y sostener vida.",
    language: "Nahar es «río» y mashqeh expresa la acción de regar. Yippared, «se dividía», introduce los cuatro cauces.",
  },
  {
    number: 11,
    title: "El Pisón y la tierra de Havila",
    summary: "El primer río rodea una región asociada con recursos valiosos.",
    hebrew: "שֵׁם הָאֶחָד פִּישׁוֹן",
    transliteration: "Shem haejad Pishon",
    rvr: "El Pisón circunda la tierra de Havila, donde hay oro.",
    ntv: "La descripción relaciona el río con una tierra rica.",
    lbla: "El primer cauce se vincula con Havila y sus recursos.",
    exact: false,
    exegesis: "La identificación moderna del Pisón y Havila es incierta. La función literaria es presentar un mundo real y abundante; el relato no ofrece datos suficientes para reconstruir con seguridad un mapa del Edén.",
    language: "Sovev significa «rodear» o «recorrer alrededor». Los nombres propios antiguos no siempre permiten equivalencias geográficas precisas.",
  },
  {
    number: 12,
    title: "La bondad de los recursos creados",
    summary: "El oro de aquella tierra es descrito como bueno junto con resina aromática y piedra preciosa.",
    hebrew: "וּזְהַב הָאָרֶץ הַהִוא טוֹב",
    transliteration: "Uzahav haaretz hahi tov",
    rvr: "La región posee oro bueno, bedelio y ónice.",
    ntv: "Los materiales valiosos forman parte de la generosidad creada.",
    lbla: "La tierra contiene recursos apreciados y declarados buenos.",
    exact: false,
    exegesis: "Los materiales reaparecerán en contextos de santuario y adoración. Su bondad no reside solo en valor económico: pertenecen a la creación de Dios y deben recibirse y administrarse bajo su voluntad.",
    language: "Bedolaj suele traducirse «bedelio», aunque su identificación exacta es discutida. Shoham designa una piedra preciosa, tradicionalmente ónice.",
  },
  {
    number: 13,
    title: "El río Guihón",
    summary: "El segundo río rodea la tierra llamada Cus.",
    hebrew: "וְשֵׁם־הַנָּהָר הַשֵּׁנִי גִּיחוֹן",
    transliteration: "Veshem-hanahar hasheni Gijon",
    rvr: "El Guihón recorre la tierra de Cus.",
    ntv: "El segundo cauce amplía la geografía del relato.",
    lbla: "El río Guihón queda asociado con Cus.",
    exact: false,
    exegesis: "La localización de este Cus no puede establecerse con certeza solamente desde el texto. El interés principal continúa siendo la extensión del agua y la fertilidad desde Edén.",
    language: "Gijon se relaciona con una raíz que expresa «brotar». La repetición numerada organiza cuidadosamente los cuatro ríos.",
  },
  {
    number: 14,
    title: "Tigris y Éufrates",
    summary: "El tercer y cuarto río se relacionan con territorios conocidos del antiguo Cercano Oriente.",
    hebrew: "הוּא הַהֹלֵךְ קִדְמַת אַשּׁוּר",
    transliteration: "Hu haholekh qidmat Ashur",
    rvr: "El Hidekel corre hacia Asiria y el cuarto río es el Éufrates.",
    ntv: "Dos ríos conocidos conectan la escena con la geografía antigua.",
    lbla: "El Tigris y el Éufrates cierran la enumeración.",
    exact: false,
    exegesis: "Tigris y Éufrates son reconocibles, pero su curso posterior a los acontecimientos de Génesis no resuelve por sí solo la ubicación del jardín. El texto mezcla referencias conocidas con otras no identificables.",
    language: "Jiddeqel es el nombre hebreo del Tigris. Perat corresponde al Éufrates, tan conocido que no necesita descripción adicional.",
  },
  {
    number: 15,
    title: "Trabajar y guardar el jardín",
    summary: "Dios coloca al ser humano en el jardín para servirlo y protegerlo.",
    hebrew: "לְעָבְדָהּ וּלְשָׁמְרָהּ",
    transliteration: "Leovdah uleshomrah",
    rvr: "El hombre recibe la tarea de labrar y guardar el huerto.",
    ntv: "La vocación humana combina desarrollo responsable y cuidado.",
    lbla: "El servicio y la custodia definen el trabajo en el jardín.",
    exact: false,
    exegesis: "El trabajo existe antes de la caída y por ello es parte de la vocación buena de la humanidad. Los mismos verbos describen más adelante servicio y guardia sacerdotal, lo que permite ver el jardín como espacio de presencia y responsabilidad sagrada.",
    language: "Avad significa «trabajar» o «servir»; shamar, «guardar», «vigilar» u «obedecer». Juntos expresan cultivo sin explotación.",
  },
  {
    number: 16,
    title: "Libertad abundante bajo la palabra",
    summary: "Dios permite comer libremente de todos los árboles del jardín.",
    hebrew: "מִכֹּל עֵץ־הַגָּן אָכֹל תֹּאכֵל",
    transliteration: "Mikkol ets-hagan akhol tokhel",
    rvr: "El mandato comienza con una amplia autorización para comer.",
    ntv: "La generosidad divina precede al único límite.",
    lbla: "La libertad humana se desarrolla dentro del don de Dios.",
    exact: false,
    exegesis: "La primera palabra moral dirigida al hombre enfatiza libertad, no restricción. El límite del versículo siguiente debe leerse dentro de esta abundancia. La obediencia bíblica responde a una gracia ya recibida.",
    language: "La construcción akhol tokhel combina infinitivo y verbo para intensificar: «ciertamente podrás comer» o «podrás comer libremente».",
  },
  {
    number: 17,
    title: "El límite que protege la vida",
    summary: "Dios prohíbe comer de un árbol y advierte que la desobediencia conduce a la muerte.",
    hebrew: "מוֹת תָּמוּת",
    transliteration: "Mot tamut",
    rvr: "Comer del árbol prohibido traerá muerte.",
    ntv: "Rechazar el límite divino rompe la comunión que sostiene la vida.",
    lbla: "La advertencia une desobediencia y certeza de muerte.",
    exact: false,
    exegesis: "El mandato hace posible una obediencia real. La muerte anunciada comienza como ruptura y expulsión, y culmina en mortalidad física. No hay contradicción en que la sentencia se manifieste en un proceso que empieza el día de la rebelión.",
    language: "Mot tamut es otra construcción intensiva: «ciertamente morirás». Beyom puede señalar «cuando» o el inicio cierto de la consecuencia, según el contexto.",
  },
  {
    number: 18,
    title: "No es bueno que el ser humano esté solo",
    summary: "Por primera vez algo es declarado no bueno: la soledad del hombre frente a su misión.",
    hebrew: "לֹא־טוֹב הֱיוֹת הָאָדָם לְבַדּוֹ",
    transliteration: "Lo-tov heyot haadam levado",
    rvr: "Dios decide hacer una ayuda adecuada para el hombre.",
    ntv: "La humanidad necesita una compañera que corresponda a su dignidad y misión.",
    lbla: "La solución divina será una ayuda frente a él, semejante y complementaria.",
    exact: false,
    exegesis: "La frase no presenta a la mujer como asistente inferior. Dios mismo es llamado ayuda de su pueblo en otros textos. La expresión señala una persona que corresponde al hombre, capaz de compartir la vocación y la relación.",
    language: "Ezer es «ayuda» poderosa; kenegdo significa «correspondiente a él» o «frente a él». La combinación comunica igualdad relacional y complementariedad.",
  },
  {
    number: 19,
    title: "Nombrar dentro del mundo creado",
    summary: "Dios lleva los animales al hombre para que los nombre.",
    hebrew: "לִרְאוֹת מַה־יִּקְרָא־לוֹ",
    transliteration: "Lirot mah-yiqra-lo",
    rvr: "El hombre asigna nombres a las criaturas presentadas por Dios.",
    ntv: "La tarea de nombrar expresa discernimiento y autoridad delegada.",
    lbla: "Dios incorpora al ser humano en la administración del mundo animal.",
    exact: false,
    exegesis: "Nombrar manifiesta la función representativa de la humanidad, pero la autoridad sigue siendo delegada porque Dios forma y presenta los animales. La escena también permite reconocer que ninguno corresponde plenamente al hombre.",
    language: "Qara significa «llamar» o «nombrar». El texto usa nephesh jayyah para «ser viviente», la misma expresión aplicada al hombre en el versículo 7.",
  },
  {
    number: 20,
    title: "Ninguna criatura corresponde al hombre",
    summary: "Después de nombrar a los animales, no se encuentra entre ellos una ayuda adecuada.",
    hebrew: "וּלְאָדָם לֹא־מָצָא עֵזֶר כְּנֶגְדּוֹ",
    transliteration: "Uleadam lo-matsa ezer kenegdo",
    rvr: "No se halla para el hombre una ayuda que le corresponda.",
    ntv: "La diferencia humana se vuelve evidente antes de la creación de la mujer.",
    lbla: "La búsqueda prepara literariamente el reconocimiento de la compañera.",
    exact: false,
    exegesis: "La escena no informa a Dios de algo desconocido; conduce al hombre a percibir su necesidad. La comunidad humana no puede ser sustituida por dominio sobre los animales.",
    language: "Matsa, «hallar», aparece en forma impersonal dentro de la frase. La repetición de ezer kenegdo conecta directamente con la intención divina del versículo 18.",
  },
  {
    number: 21,
    title: "Dios inicia una nueva obra",
    summary: "Dios hace caer un sueño profundo, toma del costado del hombre y cierra el lugar.",
    hebrew: "וַיַּפֵּל יְהוָה אֱלֹהִים תַּרְדֵּמָה",
    transliteration: "Vayyappel Adonai Elohim tardemah",
    rvr: "Un sueño profundo precede a la formación de la mujer.",
    ntv: "El hombre permanece pasivo mientras Dios provee la compañera.",
    lbla: "La iniciativa y la acción pertenecen enteramente a Dios.",
    exact: false,
    exegesis: "El sueño subraya que la relación no es fabricación ni logro del hombre. La mujer procede de la misma humanidad y es obra directa de Dios. El término anatómico puede referirse a costado, no solamente a una costilla aislada.",
    language: "Tardemah es «sueño profundo» inducido por Dios. Tsela suele significar «lado» o «costado» y también describe lados de estructuras.",
  },
  {
    number: 22,
    title: "La mujer es presentada por Dios",
    summary: "Dios construye una mujer del costado tomado y la lleva al hombre.",
    hebrew: "וַיִּבֶן יְהוָה אֱלֹהִים אֶת־הַצֵּלָע לְאִשָּׁה",
    transliteration: "Vayyiven Adonai Elohim et-hatsela leishah",
    rvr: "Dios forma a la mujer y la presenta al hombre.",
    ntv: "La compañera es un don personal del Creador.",
    lbla: "La acción divina establece el encuentro humano.",
    exact: false,
    exegesis: "La presentación tiene resonancias de una entrega nupcial. Ambos reciben su existencia y relación de Dios; por ello la unión no se basa en posesión, sino en reconocimiento agradecido y responsabilidad mutua.",
    language: "Banah, «construir», contrasta artísticamente con yatsar, «formar», del versículo 7. Ishah, «mujer», prepara el juego sonoro con ish, «varón».",
  },
  {
    number: 23,
    title: "Reconocimiento de una humanidad compartida",
    summary: "El hombre celebra que la mujer comparte su misma carne y hueso.",
    hebrew: "עֶצֶם מֵעֲצָמַי וּבָשָׂר מִבְּשָׂרִי",
    transliteration: "Etsem me'atsamai uvasar mibbesari",
    rvr: "El hombre reconoce en la mujer hueso de sus huesos y carne de su carne.",
    ntv: "La primera palabra humana registrada es una exclamación de parentesco y unidad.",
    lbla: "La igualdad de naturaleza fundamenta la relación.",
    exact: false,
    exegesis: "La poesía expresa alegría, identidad compartida y diferencia personal. «Carne y hueso» es lenguaje de parentesco, no una definición biológica exhaustiva. El nombre reconoce semejanza, no superioridad.",
    language: "Happaam significa «esta vez» o «por fin». El juego ish/ishah funciona en hebreo como celebración literaria, aunque no pretende explicar científicamente la etimología.",
  },
  {
    number: 24,
    title: "Pacto de unión y una sola carne",
    summary: "El matrimonio establece una nueva lealtad familiar en la que varón y mujer forman una unidad.",
    hebrew: "וְדָבַק בְּאִשְׁתּוֹ וְהָיוּ לְבָשָׂר אֶחָד",
    transliteration: "Vedavaq beishto vehayu levasar ejad",
    rvr: "El hombre deja a sus padres, se une a su mujer y llegan a ser una sola carne.",
    ntv: "La alianza matrimonial crea una nueva unidad de vida.",
    lbla: "Dejar, adherirse y ser una carne describen la permanencia del vínculo.",
    exact: false,
    exegesis: "El narrador formula un principio que Jesús citará al enseñar sobre matrimonio. «Una sola carne» incluye unión corporal, parentesco, fidelidad y proyecto compartido; no elimina la identidad personal de los cónyuges.",
    language: "Davaq significa «adherirse con firmeza» y se usa también para lealtad de pacto. Basar ejad, «una carne», expresa unidad concreta y relacional.",
  },
  {
    number: 25,
    title: "Desnudez sin vergüenza",
    summary: "El hombre y la mujer viven desnudos sin temor, ocultamiento ni vergüenza.",
    hebrew: "וְלֹא יִתְבֹּשָׁשׁוּ",
    transliteration: "Velo yitboshashu",
    rvr: "Ambos están desnudos y no se avergüenzan.",
    ntv: "La relación original está marcada por transparencia y seguridad.",
    lbla: "La ausencia de vergüenza retrata integridad antes del pecado.",
    exact: false,
    exegesis: "El capítulo termina con una intimidad plenamente confiada: ante Dios y entre ambos no existe necesidad de esconderse. Génesis 3 invertirá deliberadamente esta condición mediante vergüenza, temor y acusación.",
    language: "Bosh significa «avergonzarse» o «quedar deshonrado». La forma recíproca sugiere que ninguno experimentaba vergüenza ante el otro.",
  },
];

export const chapterStudies: readonly ChapterStudy[] = [
  {
    key: "GEN-1",
    bookId: "GEN",
    bookSlug: "genesis",
    bookName: "Génesis",
    testament: "Antiguo Testamento",
    section: "Pentateuco",
    chapter: 1,
    chapterCount: 50,
    lessonLabel: "Primera lección",
    title: "En el principio",
    introduction: "Génesis 1 presenta a Dios como Creador soberano y ordena el mundo mediante su palabra. Empezamos con el texto, su contexto y su significado antes de evaluar debates posteriores.",
    verses: genesis1Verses,
    theology: [
      { title: "Dios es anterior a la creación", text: "El relato distingue radicalmente al Creador de todo lo creado." },
      { title: "La creación tiene propósito", text: "El orden y la evaluación divina muestran intención, no azar teológico." },
      { title: "La palabra divina es eficaz", text: "Lo que Dios dispone llega a existir y cumple su función." },
      { title: "Cristo y la creación", text: "El Nuevo Testamento identifica al Hijo como agente de la creación sin borrar la unidad de Dios." },
    ],
    doctrinalNote: "La creación de la nada se formula con mayor claridad al leer Génesis junto con pasajes como Hebreos 11:3. No conviene exigir que Génesis 1:1 responda por sí solo a todas las preguntas filosóficas posteriores.",
    connections: genesis1Connections,
  },
  {
    key: "GEN-2",
    bookId: "GEN",
    bookSlug: "genesis",
    bookName: "Génesis",
    testament: "Antiguo Testamento",
    section: "Pentateuco",
    chapter: 2,
    chapterCount: 50,
    lessonLabel: "Segunda lección",
    title: "El huerto y la vocación humana",
    introduction: "Génesis 2 enfoca la creación desde la experiencia humana: reposo, tierra, trabajo, límite, comunión y matrimonio. El capítulo amplía el relato anterior y presenta la vida como don recibido bajo la palabra de Dios.",
    verses: genesis2Verses,
    theology: [
      { title: "El reposo corona la creación", text: "El séptimo día orienta el trabajo y el tiempo hacia la comunión y el gobierno de Dios." },
      { title: "La humanidad recibe una vocación", text: "Trabajar y guardar describen servicio responsable dentro de una creación que pertenece a Dios." },
      { title: "La libertad necesita un límite", text: "La obediencia reconoce que la sabiduría moral procede del Creador y no de la autonomía humana." },
      { title: "La comunión forma parte del diseño", text: "Varón y mujer comparten dignidad, humanidad y una alianza de fidelidad expresada como una sola carne." },
    ],
    doctrinalNote: "Génesis 2 debe leerse como una ampliación teológica de la creación humana, no como una narración aislada que compite con Génesis 1. La expresión «ayuda correspondiente» afirma una compañera adecuada y de igual humanidad; no sustenta inferioridad.",
    connections: [
      ["Éxodo 20:8–11", "El mandamiento del sábado fundamenta el reposo de Israel en el patrón creador."],
      ["Salmo 8:4–8", "La dignidad humana se une a una responsabilidad delegada sobre la creación."],
      ["Mateo 19:4–6", "Jesús reúne Génesis 1 y 2 al enseñar sobre la unión matrimonial."],
      ["1 Corintios 15:45", "Pablo contrasta al primer Adán, ser viviente, con Cristo, dador de vida."],
      ["Apocalipsis 22:1–2", "El río y el árbol de la vida reaparecen en la consumación de la nueva creación."],
    ],
  },
  ...genesis3to10Studies,
];

export function getChapterStudy(bookId: string, chapter: number) {
  return chapterStudies.find((study) => study.bookId === bookId && study.chapter === chapter);
}

export function getChapterStudyBySlug(bookSlug: string, chapter: number) {
  return chapterStudies.find((study) => study.bookSlug === bookSlug && study.chapter === chapter);
}

export function getAvailableStudyChapters(bookId: string) {
  return chapterStudies
    .filter((study) => study.bookId === bookId)
    .map((study) => study.chapter)
    .sort((a, b) => a - b);
}
